name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '6.14.8'
          git-tag-version: 'true'
      - name: Install and Build
        run: |
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
